# Write a program to accept marks of 6 students and display them in a sorted
marks=[]
m1=int(input("enter subject marks\n"))
m2=int(input("enter subject marks\n"))
m3=int(input("enter subject marks\n"))
m4=int(input("enter subject marks\n"))
m5=int(input("enter subject marks\n"))
m6=int(input("enter subject marks\n"))
marks.append(m1)
marks.append(m2)
marks.append(m3)
marks.append(m4)
marks.append(m5)
marks.append(m6)
marks.sort()
print(marks)